<style>       .nav{       	margin-bottom: -1px;       }	   .nav li{				float: left;				height:40px;			    cursor: pointer;			    color: #666;			}					li.active{				border-bottom:solid 4px #009944;				font-weight: 600;				color:#333;			}			             .nav li span{             	display: block;             	width:50px;             	text-align: center;             	padding:0px             }             .tr-mess-content{             	height:120px;             	overflow: hidden;                      	padding-left:20px!important;             	             }           </style><div class="t b20">    <div class="tl-mess pull-left corporate-base-info" {x2;if:$msgList['number'] == '0'} style="width: 100%" {x2;endif}>        <div class="tl-mess-left pull-left" style="padding: 0px 0px;overflow:hidden;width: 23%;">            <img src="{x2;if:$_user['company_logo']}{x2;$_user['company_logo']}{x2;else}app/core/styles/images/default06.png{x2;endif}" style="width:100%;height:98%;position:relative;top:50%;left:50%;transform:translate(-50%,-50%);">        </div>        <div class="tl-mess-right pull-left">            <div class="mes-text">                <div class="com-name pull-left">{x2;$_user['company_name']}</div>                <!--<div class="yellow-text pull-right">修改企业资料</div>-->                <div class="clearfix"></div>            </div>            <div class="mes-title">                <div class="mes-title-l pull-left">                    <span id="levelhtml">                         <input type="hidden" id="level" value="{x2;$_user['company_level']}">					</span>                </div>                <div class="mes-title-r pull-left"><span>点击量：{x2;$_user['userreferrer']}</span></div>                <div class="mes-title-r pull-left"><span>收藏量：{x2;$_user['company_num']}</span></div>                <div class="clearfix"></div>            </div>        </div>        <div class="clearfix"></div>    </div>    {x2;if:$msgList['number'] > '0'}    <div class="tr-mess pull-right corporate-message-notice">        <div class="tr-mess-title">        	    <ul class="nav" id="tab_n" style="border-bottom:solid 1px rgba(255,255,255,0.2);padding-left:14px;height:40px;line-height:40px;">                                <li class="active" style="margin-right:10px;"><span>公告</span></li>                                <li><span>消息</span></li>			   </ul>        </div>        <div id="gd" style="margin-top:16px;"></div>        <!--<div class="tr-mess-content">
            <ul>
                {x2;tree:$msgList['data'],vv,cid}
                    <li>
                        {x2;if:v:vv['msg_url'] != ''}
                        <a target="_blank" href="{x2;v:vv['msg_url']}&msg_id={x2;v:vv['msg_id']}"><img src="app/core/styles/img/green-laba.png" style="margin-right:10px;width:16px;"/>{x2;v:vv['msg_title']}</a>
                        {x2;else}
                        <a target="_blank" href="index.php?user-company-message-messageinfo&msg_id={x2;v:vv['msg_id']}"><img src="app/core/styles/img/green-laba.png"/ style="width:16px;">{x2;v:vv['msg_title']}</a>
                        {x2;endif}
                    </li>
                {x2;endtree}
            </ul>
        </div>-->    </div>    {x2;endif}    <div class="clearfix"></div></div><script src="app/core/styles/js/scroll.js"></script><script>    $(function(){        var level = $('#level').val();        var htmla = '';        var htmlb = '';        var reshtml = '推荐指数：';        for (var i=0;i<level;i++)        {            htmla += "<img src='app/core/styles/images/qyhy/qy_star_on.png'>"        }        for (var j=0;j<5-level;j++)        {            htmlb += "<img src='app/core/styles/images/qyhy/qy_star.png'>"        }        reshtml += htmla + htmlb;        $('#levelhtml').html(reshtml);         $(".tr-mess-content").myScroll({					      speed: 80, //数值越大，速度越慢					      rowHeight:30 //li的高度				     });             var type=2;			  				 $("#tab_n").children("li").click(function(){				     	  $(this).addClass("active");			     	  $(this).siblings().removeClass("active");		     	  			     	  if($(this).children("span").text()=="消息"){					        type=1;					       					    }else if($(this).children("span").text()=="公告"){					        type=2;				      					    }						   message();					   			     })						 function message(){				 	 $.ajax({                         type: "get",                         url: "index.php?core-api-index-getShowMessage&type="+type,                         dataType: "json",                          success: function(data){                            	  console.log(data.data);                          	  $("#gd").empty();                         	                            	  if(data.data==""){                          	  	 $("#gd").append("<div class='tr-mess-content'><ul ><li>暂无任何消息！</li></ul><div>");                          	  }else{                          	     $("#gd").append("<div class='tr-mess-content'><ul id='express'></ul><div>");                          	  	$.each(data.data, function(i,indexs) {                          	  	  $("#express").append("<li><a  style='font-size:13px' href="+indexs.msg_url+indexs.msg_id+">"+indexs.msg_title+"</a></li>");                          	     })                          	  }                                $("div.tr-mess-content").myScroll({					                  speed: 40, //数值越大，速度越慢					                  rowHeight:30 //li的高度				               });			            	}                     })				 }				message();    });</script>